# Generated by Django 5.1.8 on 2025-06-10 16:26

import core.models.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('milestone_type', models.CharField(choices=[('delivery', 'Delivery Date'), ('payment', 'Payment Due'), ('review', 'Review Period'), ('renewal', 'Renewal Notice'), ('reporting', 'Reporting Deadline')], max_length=20)),
                ('due_date', models.DateField(db_index=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('reminder_days', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_party', models.BooleanField(default=False)),
                ('role_in_contract', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='contract_templates/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size])),
                ('is_standard_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('party_type', models.CharField(choices=[('internal', 'Internal Entity'), ('external', 'External Counterparty'), ('government', 'Government Agency'), ('third_party', 'Third Party Service Provider')], max_length=20)),
                ('legal_entity_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Address')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Auditable Model',
                'verbose_name_plural': 'Auditable Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_terms', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Payment Terms')),
                ('governing_law', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('termination_clause', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Termination Clause')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('renewal_pending', 'Renewal Pending'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='draft', max_length=20)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('compliance_obligations', models.ManyToManyField(blank=True, related_name='linked_contracts', to='compliance.complianceobligation')),
            ],
        ),
    ]
