# Generated by Django 5.1.8 on 2025-05-02 11:04

import core.models.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0005_archivedorganization_organization_required_archivedorganization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='contract_templates/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size])),
                ('is_standard_template', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_terms', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Payment Terms')),
                ('governing_law', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('termination_clause', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Termination Clause')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('renewal_pending', 'Renewal Pending'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='draft', max_length=20)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('compliance_obligations', models.ManyToManyField(blank=True, related_name='linked_contracts', to='compliance.complianceobligation')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contracttype')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('party_type', models.CharField(choices=[('internal', 'Internal Entity'), ('external', 'External Counterparty'), ('government', 'Government Agency'), ('third_party', 'Third Party Service Provider')], max_length=20)),
                ('legal_entity_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Address')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Auditable Model',
                'verbose_name_plural': 'Auditable Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_party', models.BooleanField(default=False)),
                ('role_in_contract', models.CharField(max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.party')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='parties',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractParty', to='contracts.party'),
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('milestone_type', models.CharField(choices=[('delivery', 'Delivery Date'), ('payment', 'Payment Due'), ('review', 'Review Period'), ('renewal', 'Renewal Notice'), ('reporting', 'Reporting Deadline')], max_length=20)),
                ('due_date', models.DateField(db_index=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('reminder_days', models.IntegerField(default=7)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'indexes': [models.Index(fields=['contract', 'milestone_type'], name='contracts_c_contrac_7951c5_idx'), models.Index(fields=['due_date'], name='contracts_c_due_dat_af75dd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_contractmilestone')],
            },
        ),
        migrations.AddIndex(
            model_name='contracttype',
            index=models.Index(fields=['organization', 'is_standard_template'], name='contracts_c_organiz_4d8132_idx'),
        ),
        migrations.AddConstraint(
            model_name='contracttype',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_contracttype'),
        ),
        migrations.AlterUniqueTogether(
            name='contracttype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='contractparty',
            unique_together={('contract', 'party')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'status'], name='contracts_c_organiz_ebd2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='contracts_c_start_d_f953e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_contract'),
        ),
    ]
