# Generated by Django 5.1.8 on 2025-06-10 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contracttype',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contracttype'),
        ),
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='party',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.party'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parties',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractParty', to='contracts.party'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['contract', 'milestone_type'], name='contracts_c_contrac_7951c5_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['due_date'], name='contracts_c_due_dat_af75dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_contractmilestone'),
        ),
        migrations.AddIndex(
            model_name='contracttype',
            index=models.Index(fields=['organization', 'is_standard_template'], name='contracts_c_organiz_4d8132_idx'),
        ),
        migrations.AddConstraint(
            model_name='contracttype',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_contracttype'),
        ),
        migrations.AlterUniqueTogether(
            name='contracttype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='contractparty',
            unique_together={('contract', 'party')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'status'], name='contracts_c_organiz_ebd2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='contracts_c_start_d_f953e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_contract'),
        ),
    ]
