# Generated by Django 5.1.8 on 2025-08-16 12:33

from django.db import migrations, models
import django.db.models.deletion


def set_default_organization(apps, schema_editor):
    """Set default organization for existing Party records"""
    Party = apps.get_model('contracts', 'Party')
    Organization = apps.get_model('organizations', 'Organization')
    
    # Get the first organization as default
    default_org = Organization.objects.first()
    if default_org:
        Party.objects.filter(organization__isnull=True).update(organization=default_org)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('contracts', '0002_initial'),
    ]

    operations = [
        # Add organization field as nullable first
        migrations.AddField(
            model_name='party',
            name='organization',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='organizations.organization',
                verbose_name='Organization'
            ),
        ),
        
        # Set default organization for existing records
        migrations.RunPython(set_default_organization, reverse_code=migrations.RunPython.noop),
        
        # Make organization field non-nullable
        migrations.AlterField(
            model_name='party',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='organizations.organization',
                verbose_name='Organization'
            ),
        ),
        
        # Add unique constraint
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('organization', 'name')},
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['organization', 'party_type'], name='contracts_party_org_party_idx'),
        ),
        
        # Add constraint
        migrations.AddConstraint(
            model_name='party',
            constraint=models.CheckConstraint(
                check=models.Q(organization__isnull=False),
                name='organization_required_party'
            ),
        ),
    ]
