# Generated by Django 5.1.8 on 2025-08-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20250816_1233'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={},
        ),
        migrations.RenameIndex(
            model_name='party',
            new_name='contracts_p_organiz_11e1d2_idx',
            old_name='contracts_party_org_party_idx',
        ),
        migrations.AlterField(
            model_name='party',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
    ]
