# Generated by Django 5.1.8 on 2025-06-10 16:26

import core.models.validators
import django.core.validators
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_case', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('default_priority', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='LegalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('archive_date', models.DateField(default=django.utils.timezone.now)),
                ('retention_period_years', models.IntegerField(default=7)),
                ('archive_reason', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Reason for Archiving')),
                ('destruction_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization-Owned Model',
                'verbose_name_plural': 'Organization-Owned Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('opened_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('closed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('estimated_resolution_date', models.DateField(blank=True, db_index=True, null=True)),
                ('risk_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Risk Description')),
                ('compliance_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Compliance Description')),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('investigation', 'Investigation'), ('litigation', 'Litigation'), ('settlement_negotiation', 'Settlement Negotiation'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='intake', max_length=30)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium-Low'), (3, 'Medium'), (4, 'Medium-High'), (5, 'High')], db_index=True, default=3)),
                ('internal_notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Internal Notes')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='legal_documents/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size])),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LegalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('party_type', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('witness', 'Witness'), ('third_party', 'Third Party')], max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Auditable Model',
                'verbose_name_plural': 'Auditable Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
            ],
        ),
    ]
