# Generated by Django 5.1.8 on 2025-05-02 10:50

import core.models.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0005_archivedorganization_organization_required_archivedorganization_and_more'),
        ('risk', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('default_priority', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
            ],
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('opened_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('closed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('estimated_resolution_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('investigation', 'Investigation'), ('litigation', 'Litigation'), ('settlement_negotiation', 'Settlement Negotiation'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='intake', max_length=30)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium-Low'), (3, 'Medium'), (4, 'Medium-High'), (5, 'High')], db_index=True, default=3)),
                ('internal_notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Internal Notes')),
                ('attorneys', models.ManyToManyField(blank=True, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legal.casetype')),
                ('compliance_obligations', models.ManyToManyField(blank=True, related_name='legal_cases', to='compliance.complianceobligation')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('lead_attorney', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('related_risks', models.ManyToManyField(blank=True, related_name='legal_cases', to='risk.risk')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
        migrations.CreateModel(
            name='LegalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('archive_date', models.DateField(default=django.utils.timezone.now)),
                ('retention_period_years', models.IntegerField(default=7)),
                ('archive_reason', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Reason for Archiving')),
                ('destruction_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='legal.legalcase')),
            ],
            options={
                'verbose_name': 'Organization-Owned Model',
                'verbose_name_plural': 'Organization-Owned Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_case', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.legalcase')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='legal_documents/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size])),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legal.legalcase')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
        migrations.CreateModel(
            name='LegalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('party_type', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('witness', 'Witness'), ('third_party', 'Third Party')], max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Auditable Model',
                'verbose_name_plural': 'Auditable Models',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='legalcase',
            name='parties',
            field=models.ManyToManyField(related_name='legal_cases', through='legal.CaseParty', to='legal.legalparty'),
        ),
        migrations.AddField(
            model_name='caseparty',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.legalparty'),
        ),
        migrations.CreateModel(
            name='LegalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='legal.legalcase')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
        migrations.AddIndex(
            model_name='casetype',
            index=models.Index(fields=['organization'], name='legal_caset_organiz_63d656_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casetype',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['case', 'is_confidential'], name='legal_legal_case_id_fbd9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='legalcase',
            index=models.Index(fields=['organization', 'status'], name='legal_legal_organiz_dbddbc_idx'),
        ),
        migrations.AddIndex(
            model_name='legalcase',
            index=models.Index(fields=['opened_date', 'closed_date'], name='legal_legal_opened__6149ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseparty',
            unique_together={('case', 'party')},
        ),
        migrations.AddIndex(
            model_name='legaltask',
            index=models.Index(fields=['case', 'status'], name='legal_legal_case_id_914427_idx'),
        ),
        migrations.AddIndex(
            model_name='legaltask',
            index=models.Index(fields=['due_date'], name='legal_legal_due_dat_e80402_idx'),
        ),
    ]
