# Generated by Django 5.1.8 on 2025-05-02 14:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalcase',
            name='compliance_obligations',
        ),
        migrations.RemoveField(
            model_name='legalcase',
            name='related_risks',
        ),
        migrations.AddField(
            model_name='legalcase',
            name='compliance_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Compliance Description'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='risk_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Risk Description'),
        ),
    ]
