# Generated by Django 5.1.8 on 2025-07-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalparty',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this party', on_delete=django.db.models.deletion.CASCADE, related_name='legalparty_set', to='organizations.organization'),
        ),
    ]
