# Generated by Django 5.1.14 on 2025-12-09 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('key', models.CharField(help_text='Configuration key', max_length=100, unique=True, verbose_name='Configuration Key')),
                ('value', models.JSONField(help_text='Configuration value (JSON)', verbose_name='Configuration Value')),
                ('description', models.TextField(blank=True, help_text='Description of this configuration', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active', verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'db_table': 'services_ai_aiconfiguration',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('prompt', models.TextField(help_text='The user prompt sent to LLM', verbose_name='Prompt')),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt used for LLM', null=True, verbose_name='System Prompt')),
                ('response', models.TextField(blank=True, help_text='LLM response', null=True, verbose_name='Response')),
                ('model', models.CharField(blank=True, help_text='LLM model used (e.g., gemma:2b, gpt-3.5-turbo)', max_length=128, null=True, verbose_name='Model')),
                ('provider', models.CharField(default='deepseek', help_text='LLM provider (deepseek, ollama, openai)', max_length=64, verbose_name='Provider')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens consumed', null=True, verbose_name='Tokens Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('extra', models.JSONField(blank=True, help_text='Additional metadata (e.g., job_id, raw_response)', null=True, verbose_name='Extra Data')),
                ('question', models.TextField(blank=True, help_text="Legacy: The user's question (use prompt instead)", null=True, verbose_name='Question')),
                ('source', models.CharField(blank=True, choices=[('faq', 'FAQ'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama'), ('openai', 'OpenAI')], help_text='Legacy: Which source provided the response', max_length=20, null=True, verbose_name='Response Source')),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to generate response', null=True, verbose_name='Processing Time (seconds)')),
                ('success', models.BooleanField(default=True, help_text='Whether the interaction was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the interaction failed', verbose_name='Error Message')),
                ('user_feedback', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='User feedback on the response quality', max_length=10, null=True, verbose_name='User Feedback')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the interaction', verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to='organizations.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Interaction',
                'verbose_name_plural': 'AI Interactions',
                'db_table': 'services_ai_aiinteraction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='services_ai_user_id_172f43_idx'), models.Index(fields=['organization', '-created_at'], name='services_ai_organiz_e4e77e_idx'), models.Index(fields=['provider', '-created_at'], name='services_ai_provide_40d959_idx'), models.Index(fields=['model', '-created_at'], name='services_ai_model_3c925a_idx'), models.Index(fields=['source', '-created_at'], name='services_ai_source_ccbc93_idx'), models.Index(fields=['success', '-created_at'], name='services_ai_success_bbec5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('category', models.CharField(help_text='Category of the knowledge base entry', max_length=50, verbose_name='Category')),
                ('question', models.TextField(help_text='The question or topic', verbose_name='Question')),
                ('answer', models.TextField(help_text='The answer or explanation', verbose_name='Answer')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords for matching questions', verbose_name='Keywords')),
                ('priority', models.IntegerField(default=1, help_text='Priority for matching (higher = more important)', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this entry is active', verbose_name='Active')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this entry has been used', verbose_name='Usage Count')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'AI Knowledge Base Entry',
                'verbose_name_plural': 'AI Knowledge Base Entries',
                'db_table': 'services_ai_aiknowledgebase',
                'ordering': ['-priority', '-usage_count'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='services_ai_categor_415d38_idx'), models.Index(fields=['is_active', '-priority'], name='services_ai_is_acti_ab2804_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Session identifier for grouping conversations', max_length=128, null=True, verbose_name='Session ID')),
                ('query', models.TextField(help_text="User's query or question", verbose_name='Query')),
                ('response', models.TextField(blank=True, help_text='AI assistant response', null=True, verbose_name='Response')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata (e.g., model, tokens, duration)', null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='organizations.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat Log',
                'verbose_name_plural': 'Chat Logs',
                'db_table': 'services_ai_chatlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='services_ai_user_id_36cf53_idx'), models.Index(fields=['organization', '-created_at'], name='services_ai_organiz_61673d_idx'), models.Index(fields=['session_id', '-created_at'], name='services_ai_session_04a222_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='Key')),
                ('title', models.CharField(help_text='Human-readable title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of what this template does', verbose_name='Description')),
                ('template', models.TextField(help_text='Prompt template with placeholders like {{issue_description}}', verbose_name='Template')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template for its key', verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this template belongs to (null for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='organizations.organization', verbose_name='Organization')),
                ('owner', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'db_table': 'services_ai_prompttemplate',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key', 'organization'], name='services_ai_key_38e7f2_idx'), models.Index(fields=['is_default', 'organization'], name='services_ai_is_defa_244b5c_idx')],
            },
        ),
    ]
