# Generated by Django 5.1.8 on 2025-04-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object that was changed', verbose_name='object id')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], help_text='The type of change that was made', max_length=50, verbose_name='action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='The changes that were made to the object', verbose_name='changes')),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=200, verbose_name='object representation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this change was made', verbose_name='timestamp')),
                ('model', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('content_type', models.ForeignKey(help_text='The type of object that was changed', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
