# Generated by Django 5.1.8 on 2025-06-10 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0001_initial'),
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Select a user as owner, or leave blank to specify an email below.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.risk'),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.complianceobligation'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='regulatory_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancerequirement'),
        ),
        migrations.AddField(
            model_name='documentprocessing',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Select a user as owner, or leave blank to specify an email below.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='documentprocessing',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.policydocument'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='policy_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.policydocument'),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.policydocument'),
        ),
        migrations.AddIndex(
            model_name='complianceframework',
            index=models.Index(fields=['organization', 'regulatory_body'], name='compliance__organiz_3f52b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceframework',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_complianceframework'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceframework',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='complianceobligation',
            index=models.Index(fields=['due_date'], name='compliance__due_dat_13b1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceobligation',
            index=models.Index(fields=['status'], name='compliance__status_5e1918_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceobligation',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_complianceobligation'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceobligation',
            unique_together={('requirement', 'obligation_id')},
        ),
        migrations.AddConstraint(
            model_name='policydocument',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_policydocument'),
        ),
        migrations.AddConstraint(
            model_name='documentprocessing',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_documentprocessing'),
        ),
        migrations.AddIndex(
            model_name='compliancerequirement',
            index=models.Index(fields=['regulatory_framework'], name='compliance__regulat_a01888_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancerequirement',
            index=models.Index(fields=['policy_document'], name='compliance__policy__b21d24_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancerequirement',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_compliancerequirement'),
        ),
        migrations.AddIndex(
            model_name='complianceevidence',
            index=models.Index(fields=['validity_start', 'validity_end'], name='compliance__validit_bb6dfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceevidence',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_complianceevidence'),
        ),
    ]
