# Generated by Django 5.1.8 on 2025-05-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceevidence',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.policydocument'),
        ),
    ]
