# Generated by Django 5.1.14 on 2026-05-23 18:50

import core.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_financialcontrolframework_financialcontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocument',
            name='file',
            field=models.FileField(upload_to='policy_documents/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size]),
        ),
    ]
