# Generated by Django 5.1.8 on 2025-08-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head_of_unit', 'Head of Unit'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', help_text='Role of the user within their organization.', max_length=50, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head_of_unit', 'Head of Unit'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head_of_unit', 'Head of Unit'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=50),
        ),
    ]
