# Generated by Django 5.1.8 on 2025-06-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
