# Generated by Django 5.1.8 on 2025-08-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_head_of_unit_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_created',
            field=models.BooleanField(default=False, help_text='Whether this user was created by an admin (requires first-time setup).', verbose_name='Admin Created'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_first_time_setup_complete',
            field=models.BooleanField(default=False, help_text='Whether the user has completed their first-time setup (OTP verification and password reset).', verbose_name='First Time Setup Complete'),
        ),
    ]
