# Generated by Django 5.1.8 on 2025-09-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_email_preferences_and_logging'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='users_email_user_id_628d1c_idx',
            old_name='users_emai_user_id_4a8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='users_email_recipie_1474e7_idx',
            old_name='users_emai_recipie_8b2b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='users_email_created_48fce1_idx',
            old_name='users_emai_created_9b2b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='users_email_status_3f3997_idx',
            old_name='users_emai_status_9b2b1a_idx',
        ),
    ]
