# Generated by Django 5.1.8 on 2025-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_users_emai_user_id_4a8b8a_idx_users_email_user_id_628d1c_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='otp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_expired', False), ('is_verified', False)), fields=('user',), name='unique_active_otp_per_user'),
        ),
    ]
