# Generated by Django 5.1.14 on 2026-05-23 18:50

import core.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_otp_unique_active_otp_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', help_text="User's avatar image.", upload_to='avatars/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='Profile Picture'),
        ),
    ]
