# Generated by Django 5.1.8 on 2025-06-10 16:26

import core.models.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('file', models.FileField(upload_to='media/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size], verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('request_name', models.CharField(db_index=True, max_length=255, verbose_name='Request Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size], verbose_name='File')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('date_of_request', models.DateField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('requestee_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Requestee Email')),
                ('requestee_identifier', models.CharField(help_text='Enter details about the requestee (team, department, etc.)', max_length=255, verbose_name='Requestee Identifier')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('upload_token', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True)),
                ('token_expiry', models.DateTimeField(blank=True, help_text='When the upload link expires.', null=True)),
            ],
            options={
                'verbose_name': 'Document Request',
                'verbose_name_plural': 'Document Requests',
                'ordering': ['-date_of_request', 'request_name'],
            },
        ),
    ]
