# Generated by Django 5.1.8 on 2025-05-02 11:01

import core.models.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_archivedorganization_organization_required_archivedorganization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('request_name', models.CharField(db_index=True, max_length=255, verbose_name='Request Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size], verbose_name='File')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('date_of_request', models.DateField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('requestee_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Requestee Email')),
                ('requestee_identifier', models.CharField(help_text='Enter details about the requestee (team, department, etc.)', max_length=255, verbose_name='Requestee Identifier')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('request_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Request Owner')),
                ('requestee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Requestee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Document Request',
                'verbose_name_plural': 'Document Requests',
                'ordering': ['-date_of_request', 'request_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('file', models.FileField(upload_to='media/', validators=[core.models.validators.validate_file_extension, core.models.validators.validate_file_size], verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_management.documentrequest', verbose_name='Document Request')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['organization'], name='document_ma_organiz_2cc4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['request_name'], name='document_ma_request_fe8386_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['status'], name='document_ma_status_15866a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['due_date'], name='document_ma_due_dat_ec5c74_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['request_owner'], name='document_ma_request_756a4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_documentrequest'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization'], name='document_ma_organiz_3035b4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_request'], name='document_ma_documen_30dabf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='document_ma_uploade_53424f_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_document'),
        ),
    ]
