# Generated by Django 5.1.8 on 2025-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='token_expiry',
            field=models.DateTimeField(blank=True, help_text='When the upload link expires.', null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='upload_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
