# Generated by Django 5.1.14 on 2026-05-23 18:50

import core.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0003_document_uploaded_by_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='File'),
        ),
    ]
