# Generated by Django 5.1.8 on 2025-09-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetasset',
            name='contains_pii',
            field=models.BooleanField(default=False, help_text='Whether this dataset contains PII'),
        ),
        migrations.AddField(
            model_name='datasetasset',
            name='data_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', help_text='Data classification level', max_length=20),
        ),
        migrations.AddField(
            model_name='datasetasset',
            name='encryption_key_id',
            field=models.CharField(blank=True, help_text='Encryption key identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasetasset',
            name='retention_date',
            field=models.DateTimeField(blank=True, help_text='Data retention expiration date', null=True),
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='contains_pii',
            field=models.BooleanField(default=False, help_text='Whether this artifact contains PII'),
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='data_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', help_text='Data classification level', max_length=20),
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='encryption_key_id',
            field=models.CharField(blank=True, help_text='Encryption key identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='retention_date',
            field=models.DateTimeField(blank=True, help_text='Data retention expiration date', null=True),
        ),
        migrations.AddField(
            model_name='modelasset',
            name='contains_pii',
            field=models.BooleanField(default=False, help_text='Whether this model processes PII'),
        ),
        migrations.AddField(
            model_name='modelasset',
            name='data_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', help_text='Data classification level', max_length=20),
        ),
        migrations.AddField(
            model_name='modelasset',
            name='encryption_key_id',
            field=models.CharField(blank=True, help_text='Encryption key identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='contains_pii',
            field=models.BooleanField(default=False, help_text='Whether this test result contains PII'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='data_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', help_text='Data classification level', max_length=20),
        ),
        migrations.AddField(
            model_name='testresult',
            name='encryption_key_id',
            field=models.CharField(blank=True, help_text='Encryption key identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='contains_pii',
            field=models.BooleanField(default=False, help_text='Whether this test run processes PII'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='data_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', help_text='Data classification level', max_length=20),
        ),
        migrations.AddField(
            model_name='testrun',
            name='encryption_key_id',
            field=models.CharField(blank=True, help_text='Encryption key identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='retention_date',
            field=models.DateTimeField(blank=True, help_text='Data retention expiration date', null=True),
        ),
    ]
