# Generated by Django 5.1.8 on 2025-08-21 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('export_type', models.CharField(choices=[('full_organization', 'Full Organization Data'), ('audit_data', 'Audit Data Only'), ('risk_data', 'Risk Data Only'), ('compliance_data', 'Compliance Data Only'), ('contracts_data', 'Contracts Data Only'), ('legal_data', 'Legal Data Only'), ('document_data', 'Document Management Data Only'), ('user_data', 'User Data Only'), ('custom', 'Custom Selection')], help_text='Type of data exported', max_length=50, verbose_name='Export Type')),
                ('export_format', models.CharField(choices=[('excel', 'Excel (.xlsx)'), ('csv', 'CSV'), ('json', 'JSON'), ('pdf', 'PDF')], default='excel', help_text='Format of the exported file', max_length=10, verbose_name='Export Format')),
                ('file_path', models.CharField(blank=True, help_text='Path to the exported file', max_length=500, null=True, verbose_name='File Path')),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Size of the exported file in bytes', null=True, verbose_name='File Size (bytes)')),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, help_text='Size of the exported file in MB', max_digits=10, null=True, verbose_name='File Size (MB)')),
                ('records_exported', models.PositiveIntegerField(default=0, help_text='Number of records exported', verbose_name='Records Exported')),
                ('tables_exported', models.PositiveIntegerField(default=0, help_text='Number of database tables exported', verbose_name='Tables Exported')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the export', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the export process started', null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the export process completed', null=True, verbose_name='Completed At')),
                ('processing_time_seconds', models.PositiveIntegerField(blank=True, help_text='Time taken to process the export in seconds', null=True, verbose_name='Processing Time (seconds)')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the user who requested the export', verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent information', verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, help_text='User session ID during export', max_length=100, verbose_name='Session ID')),
                ('custom_selection', models.JSONField(blank=True, default=dict, help_text='Details of custom data selection if applicable', verbose_name='Custom Selection')),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed', verbose_name='Error Message')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the export', verbose_name='Notes')),
                ('file_expires_at', models.DateTimeField(blank=True, help_text='When the exported file will be automatically deleted', null=True, verbose_name='File Expires At')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the exported file has been deleted', verbose_name='Is Deleted')),
                ('organization', models.ForeignKey(help_text='Organization whose data was exported', on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to='organizations.organization', verbose_name='Organization')),
                ('requested_by', models.ForeignKey(help_text='User who requested the data export', on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Data Export Log',
                'verbose_name_plural': 'Data Export Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'created_at'], name='admin_modul_request_71d62d_idx'), models.Index(fields=['organization', 'created_at'], name='admin_modul_organiz_0182a9_idx'), models.Index(fields=['export_type', 'status'], name='admin_modul_export__f6e631_idx'), models.Index(fields=['status', 'created_at'], name='admin_modul_status_0cd4cb_idx'), models.Index(fields=['file_expires_at'], name='admin_modul_file_ex_95c610_idx')],
            },
        ),
    ]
