# Generated by Django 5.1.8 on 2025-08-18 13:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditworkplan',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed description of the audit workplan.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='auditworkplan',
            name='objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed Objectives of the audit workplan.', null=True, verbose_name='Objectives'),
        ),
        migrations.AlterField(
            model_name='historicalauditworkplan',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed description of the audit workplan.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalauditworkplan',
            name='objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed Objectives of the audit workplan.', null=True, verbose_name='Objectives'),
        ),
    ]
