# Generated by Django 5.1.8 on 2025-04-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'audit'), ('model__in', ['issue', 'auditworkplan', 'engagement'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
