# Generated by Django 5.1.8 on 2025-04-30 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_approval_content_type'),
        ('organizations', '0005_archivedorganization_organization_required_archivedorganization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_owner_email',
            field=models.EmailField(blank=True, help_text='If owner is not a user, enter their email here.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_owner',
            field=models.ForeignKey(blank=True, help_text='Select a user as owner, or leave blank to specify an email below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_owned', to=settings.AUTH_USER_MODEL, verbose_name='Issue Owner'),
        ),
        migrations.AddConstraint(
            model_name='auditworkplan',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_auditworkplan'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_engagement'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_issue'),
        ),
    ]
