# Generated by Django 5.1.8 on 2025-09-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_issue_audit_procedures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalissue',
            name='audit_procedures',
        ),
    ]
