# Generated by Django 5.1.8 on 2025-05-10 07:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_note_objective_procedure_procedureresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='positive_finding_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Positive Finding Notes'),
        ),
        migrations.AddField(
            model_name='procedureresult',
            name='is_positive',
            field=models.BooleanField(default=False, verbose_name='Positive Result'),
        ),
        migrations.AddField(
            model_name='procedureresult',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_results', to='audit.issue', verbose_name='Linked Issue'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Note Content'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Objective Description'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Procedure Description'),
        ),
        migrations.AlterField(
            model_name='procedureresult',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
