# Generated by Django 5.1.8 on 2025-06-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_notification_created_by_and_more'),
        ('organizations', '0006_organizationsettings_subscribed_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_items', to='organizations.organization', verbose_name='organization'),
        ),
    ]
