# Generated by Django 5.1.8 on 2025-05-10 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_issue_positive_finding_notes_and_more'),
        ('organizations', '0006_organizationsettings_subscribed_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='issue',
            name='audit_issue_engagem_81a932_idx',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='procedureresult',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='procedure_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='audit.procedureresult', verbose_name='Procedure Result'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['procedure_result'], name='audit_issue_procedu_14ce17_idx'),
        ),
    ]
