# Generated by Django 5.1.8 on 2025-10-01 18:27

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_restore_issue_risks_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='risks',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Risks'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='risks',
            field=models.TextField(blank=True, null=True, verbose_name='Risks'),
        ),
    ]
