# Generated by Django 5.1.8 on 2025-05-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_followupaction_issueretest'),
        ('organizations', '0006_organizationsettings_subscribed_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
