# Generated by Django 5.1.8 on 2025-10-01 18:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_issue_risks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalissue',
            name='risks',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Risks'),
        ),
    ]
