# Generated by Django 5.1.8 on 2025-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_add_risks_to_historicalissue'),
        ('risk', '0004_objective_risk_objectives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalissue',
            name='risks',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='risks',
        ),
        migrations.AddField(
            model_name='issue',
            name='risks',
            field=models.ManyToManyField(blank=True, help_text="Select risks from the organization's risk register that are relevant to this audit finding", related_name='audit_issues', to='risk.risk', verbose_name='Related Risks'),
        ),
    ]
