# Generated by Django 5.1.8 on 2025-05-10 11:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_issueretest_result_and_more'),
        ('organizations', '0006_organizationsettings_subscribed_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupaction',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='issueretest',
            name='issue',
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Recommendation Title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Recommendation Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audit.issue', verbose_name='Issue')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='followupaction',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_actions', to='audit.recommendation', verbose_name='Recommendation'),
        ),
        migrations.AddField(
            model_name='issueretest',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retests', to='audit.recommendation', verbose_name='Recommendation'),
        ),
    ]
