# Generated by Django 5.1.8 on 2025-05-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_remove_followupaction_issue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='note',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cleared At'),
        ),
        migrations.AddField(
            model_name='note',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed At'),
        ),
        migrations.AddField(
            model_name='note',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_closed', to=settings.AUTH_USER_MODEL, verbose_name='Closed By'),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared by Owner'), ('closed', 'Closed by Supervisor')], default='open', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('todo', 'To-Do'), ('review', 'Review'), ('review_request', 'Review Request'), ('general', 'General')], default='general', max_length=16, verbose_name='Note Type'),
        ),
    ]
