# Generated by Django 5.1.8 on 2025-10-02 06:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_fix_issue_risks_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='risks',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Describe the risks associated with this audit finding. For organizations with robust risk management, you can also link to specific risks from the risk register via the Related Risks tab.', null=True, verbose_name='Related Risks'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='risks',
        ),
        migrations.AddField(
            model_name='issue',
            name='risks',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Describe the risks associated with this audit finding. For organizations with robust risk management, you can also link to specific risks from the risk register via the Related Risks tab.', null=True, verbose_name='Related Risks'),
        ),
    ]
