# Generated by Django 5.1.8 on 2025-10-02 06:05

import django_ckeditor_5.fields
from django.db import migrations, connection


def add_risks_column_if_not_exists(apps, schema_editor):
    """
    Add the risks column to historicalissue table only if it doesn't already exist.
    This prevents the migration from failing if the column already exists.
    """
    with connection.cursor() as cursor:
        # Check if the column already exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'audit_historicalissue' 
            AND column_name = 'risks'
        """)
        
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE audit_historicalissue 
                ADD COLUMN risks TEXT NULL
            """)
            print("Added 'risks' column to audit_historicalissue table")
        else:
            print("'risks' column already exists in audit_historicalissue table")


def remove_risks_column_if_exists(apps, schema_editor):
    """
    Remove the risks column from historicalissue table if it exists.
    """
    with connection.cursor() as cursor:
        # Check if the column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'audit_historicalissue' 
            AND column_name = 'risks'
        """)
        
        if cursor.fetchone():
            # Column exists, remove it
            cursor.execute("""
                ALTER TABLE audit_historicalissue 
                DROP COLUMN risks
            """)
            print("Removed 'risks' column from audit_historicalissue table")
        else:
            print("'risks' column does not exist in audit_historicalissue table")


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_fix_issue_risks_column'),
    ]

    operations = [
        migrations.RunPython(
            add_risks_column_if_not_exists,
            remove_risks_column_if_exists,
        ),
        # Skip the RemoveField and AddField operations since the field already exists as CKEditor5Field
        # The field is already in the correct state from previous migrations
    ]
