# Generated by Django 5.1.8 on 2025-05-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='project_objectives',
        ),
    ]
