# Generated by Django 5.1.8 on 2025-10-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_fix_risks_field_conflict'),
        ('risk', '0004_objective_risk_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='linked_risks',
            field=models.ManyToManyField(blank=True, help_text="Link to specific risks from the organization's risk register", related_name='audit_issues', to='risk.risk', verbose_name='Linked Risks'),
        ),
    ]
