# Generated by Django 5.1.8 on 2025-10-02 06:33

from django.db import migrations, connection


def create_table_forward(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS audit_issue_linked_risks (
                id SERIAL PRIMARY KEY,
                issue_id INTEGER NOT NULL,
                risk_id INTEGER NOT NULL,
                UNIQUE(issue_id, risk_id)
            );
        """)
        print("Created audit_issue_linked_risks table")


def create_table_reverse(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS audit_issue_linked_risks;")
        print("Dropped audit_issue_linked_risks table")


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_create_linked_risks_table'),
    ]

    operations = [
        # No-op migration - table creation is handled in migration 0014
        # This migration is kept for historical consistency but does nothing
    ]
