# Generated by Django 5.1.8 on 2025-10-02 08:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_create_linked_risks_table_final'),
        ('risk', '0004_objective_risk_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='risks',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Describe the risks associated with this audit finding. For organizations with robust risk management, you can also link to specific risks from the risk register via the Related Risks tab.', null=True, verbose_name='Related Risks'),
        ),
        migrations.AddField(
            model_name='issue',
            name='linked_risks',
            field=models.ManyToManyField(blank=True, help_text="Link to specific risks from the organization's risk register", related_name='audit_issues', to='risk.risk', verbose_name='Linked Risks'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='risks',
        ),
        migrations.AddField(
            model_name='issue',
            name='risks',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Describe the risks associated with this audit finding. For organizations with robust risk management, you can also link to specific risks from the risk register via the Related Risks tab.', null=True, verbose_name='Related Risks'),
        ),
    ]
