# Generated by Django 5.1.14 on 2026-01-22 13:11

import core.models.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_historicalissue_risks_issue_linked_risks_and_more'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEngagementDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when the record was soft-deleted', null=True, verbose_name='deleted at')),
                ('file', models.TextField(help_text='Upload a document file (PDF, DOC, DOCX, XLSX, or PPTX only)', max_length=100, validators=[core.models.validators.validate_engagement_document_extension, core.models.validators.validate_file_size, core.models.validators.validate_file_virus], verbose_name='Document File')),
                ('description', models.CharField(blank=True, help_text='Optional description for this document (e.g., "Entry Meeting Minutes", "Audit Notification")', max_length=255, null=True, verbose_name='Description')),
                ('document_type', models.CharField(blank=True, help_text='Type of document (e.g., "Entry Meeting Minutes", "Audit Notification", "Requirements List")', max_length=100, null=True, verbose_name='Document Type')),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False, verbose_name='Uploaded At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('engagement', models.ForeignKey(blank=True, db_constraint=False, help_text='The engagement this document belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.engagement', verbose_name='Engagement')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='Organization that owns this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'historical Engagement Document',
                'verbose_name_plural': 'historical Engagement Documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EngagementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when the record was soft-deleted', null=True, verbose_name='deleted at')),
                ('file', models.FileField(help_text='Upload a document file (PDF, DOC, DOCX, XLSX, or PPTX only)', upload_to='audit/engagement_documents/%Y/%m/', validators=[core.models.validators.validate_engagement_document_extension, core.models.validators.validate_file_size, core.models.validators.validate_file_virus], verbose_name='Document File')),
                ('description', models.CharField(blank=True, help_text='Optional description for this document (e.g., "Entry Meeting Minutes", "Audit Notification")', max_length=255, null=True, verbose_name='Description')),
                ('document_type', models.CharField(blank=True, help_text='Type of document (e.g., "Entry Meeting Minutes", "Audit Notification", "Requirements List")', max_length=100, null=True, verbose_name='Document Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('engagement', models.ForeignKey(help_text='The engagement this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.engagement', verbose_name='Engagement')),
                ('organization', models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Engagement Document',
                'verbose_name_plural': 'Engagement Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['engagement', '-uploaded_at'], name='audit_engag_engagem_ec0bc8_idx'), models.Index(fields=['organization', '-uploaded_at'], name='audit_engag_organiz_f336d5_idx')],
            },
        ),
    ]
