# Generated by Django 5.1.14 on 2026-05-23 18:50

import core.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_add_engagement_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementdocument',
            name='file',
            field=models.FileField(help_text='Upload a document file (PDF, DOC, DOCX, XLSX, or PPTX only)', upload_to='audit/engagement_documents/%Y/%m/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_engagement_document_extension, core.models.validators.validate_file_size, core.models.validators.validate_file_virus], verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='historicalengagementdocument',
            name='file',
            field=models.TextField(help_text='Upload a document file (PDF, DOC, DOCX, XLSX, or PPTX only)', max_length=100, validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_engagement_document_extension, core.models.validators.validate_file_size, core.models.validators.validate_file_virus], verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='historicalissueworkingpaper',
            name='file',
            field=models.TextField(max_length=100, validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='Working Paper File'),
        ),
        migrations.AlterField(
            model_name='historicalprocedure',
            name='additional_evidence',
            field=models.TextField(blank=True, help_text='Additional supporting documentation for test results', max_length=100, null=True, validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='Additional Evidence'),
        ),
        migrations.AlterField(
            model_name='historicalprocedure',
            name='evidence',
            field=models.TextField(blank=True, help_text='Primary supporting documentation for test results', max_length=100, null=True, validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='Primary Evidence'),
        ),
        migrations.AlterField(
            model_name='issueworkingpaper',
            name='file',
            field=models.FileField(upload_to='working_papers/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='Working Paper File'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='additional_evidence',
            field=models.FileField(blank=True, help_text='Additional supporting documentation for test results', null=True, upload_to='audit/procedure_evidence/%Y/%m/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='Additional Evidence'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='evidence',
            field=models.FileField(blank=True, help_text='Primary supporting documentation for test results', null=True, upload_to='audit/procedure_evidence/%Y/%m/', validators=[core.models.validators.validate_safe_filename, core.models.validators.validate_file_extension, core.models.validators.validate_file_content_signature, core.models.validators.validate_file_size], verbose_name='Primary Evidence'),
        ),
    ]
