# Generated by Django 5.1.14 on 2026-06-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_alter_engagementdocument_file_and_more'),
        ('audit', '0019_drop_procedureresult_table'),
    ]

    operations = [
    ]
