# Generated by Django 5.1.8 on 2025-06-10 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='control',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='control',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='risk',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='risk',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='risk',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='kri',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kris', to='risk.risk', verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risk.risk', verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.control', verbose_name='Control'),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.risk', verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='control',
            name='risks',
            field=models.ManyToManyField(related_name='controls', through='risk.RiskControl', to='risk.risk'),
        ),
        migrations.AddField(
            model_name='riskmatrixconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='riskmatrixconfig',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='riskmatrixconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='riskregister',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='riskregister',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='riskregister',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risk.riskregister', verbose_name='Risk Register'),
        ),
        migrations.AddIndex(
            model_name='kri',
            index=models.Index(fields=['risk'], name='risk_kri_risk_id_02a25d_idx'),
        ),
        migrations.AddIndex(
            model_name='kri',
            index=models.Index(fields=['timestamp'], name='risk_kri_timesta_16fb15_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk'], name='risk_riskas_risk_id_e2be7d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessment_date'], name='risk_riskas_assessm_58c18e_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessment_type'], name='risk_riskas_assessm_33bcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['risk'], name='risk_riskco_risk_id_944c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['control'], name='risk_riskco_control_85ba1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskcontrol',
            unique_together={('risk', 'control')},
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['organization'], name='risk_contro_organiz_710ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['code'], name='risk_contro_code_492369_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['control_owner'], name='risk_contro_control_fb78e4_idx'),
        ),
        migrations.AddIndex(
            model_name='control',
            index=models.Index(fields=['status'], name='risk_contro_status_c5522e_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmatrixconfig',
            index=models.Index(fields=['organization', 'is_active'], name='risk_riskma_organiz_0bc4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['organization', 'code'], name='risk_riskre_organiz_4a3803_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['register_name'], name='risk_riskre_registe_e540c8_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['register_period'], name='risk_riskre_registe_cac59a_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['organization'], name='risk_risk_organiz_7f8d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_register'], name='risk_risk_risk_re_357491_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['code'], name='risk_risk_code_eb37c3_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_name'], name='risk_risk_risk_na_f38719_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['category'], name='risk_risk_categor_3dadff_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['status'], name='risk_risk_status_10b721_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_owner'], name='risk_risk_risk_ow_f81fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['date_identified'], name='risk_risk_date_id_4387b9_idx'),
        ),
    ]
