# Generated by Django 5.1.8 on 2025-05-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_create_default_riskregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='code',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=16, verbose_name='Control Code'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='code',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=16, verbose_name='Risk Code'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='inherent_risk_score',
            field=models.IntegerField(default=1, editable=False, verbose_name='Inherent Risk Score'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='residual_risk_score',
            field=models.IntegerField(default=1, editable=False, verbose_name='Residual Risk Score'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_name',
            field=models.CharField(db_index=True, default='Unnamed Risk', max_length=512, verbose_name='Risk Name'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_owner',
            field=models.CharField(db_index=True, default='Unassigned', max_length=70, verbose_name='Risk Owner'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='risk.riskregister', verbose_name='Risk Register'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='code',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=16, verbose_name='Register Code'),
        ),
    ]
