# Generated by Django 5.1.8 on 2025-08-28 08:50

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('risk', '0003_cobitdomain_cobitprocess_cobitgovernance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='Objective Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Objective Name')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('origin_source', models.CharField(blank=True, help_text='Source of the objective (e.g., Strategic Plan, SDGs, internal policy)', max_length=255, null=True, verbose_name='Origin/Source')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('achieved', 'Achieved')], db_index=True, default='active', max_length=16)),
                ('is_perpetual', models.BooleanField(default=False, help_text='If true, start/end dates are optional and informational only.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_objective_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_objectives', to='organizations.organization', verbose_name='organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_objective_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='risks', to='risk.objective'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['organization', 'status'], name='risk_object_organiz_6985fd_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['code'], name='risk_object_code_2b52d9_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['name'], name='risk_object_name_4be554_idx'),
        ),
    ]
