# Generated by Django 5.2 on 2025-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('original_org_id', models.IntegerField(help_text='ID of the organization as it existed before archival.', verbose_name='Original Organization ID')),
                ('customer_code', models.CharField(db_index=True, max_length=8, verbose_name='Customer Code')),
                ('customer_name', models.CharField(db_index=True, max_length=512, verbose_name='Customer Name')),
                ('archived_reason', models.TextField(blank=True, help_text='Reason this organization was archived or unsubscribed.', verbose_name='Reason for Archiving')),
                ('financial_year_end_date', models.DateField(blank=True, null=True, verbose_name='Financial Year End Date')),
                ('customer_industry', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Industry')),
                ('logo_path', models.CharField(blank=True, help_text='Path to the archived logo file (if retained).', max_length=512, null=True, verbose_name='Archived Logo Path')),
                ('was_active', models.BooleanField(default=True, help_text='Whether the organization was active at time of archival.', verbose_name='Was Active')),
            ],
            options={
                'verbose_name': 'Archived Organization',
                'verbose_name_plural': 'Archived Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('customer_code', models.CharField(db_index=True, help_text='Unique 8-character code to identify this organization.', max_length=8, unique=True, verbose_name='Customer Code')),
                ('customer_name', models.CharField(db_index=True, help_text='The official name of the organization.', max_length=512, verbose_name='Customer Name')),
                ('financial_year_end_date', models.DateField(help_text='Closing date of the organization’s fiscal year.', verbose_name='Financial Year End Date')),
                ('logo', models.ImageField(blank=True, help_text='Optional logo for branding within the system.', null=True, upload_to='organization_logos/', verbose_name='Organization Logo')),
                ('customer_industry', models.CharField(blank=True, db_index=True, help_text='Optional industry classification for reporting.', max_length=32, null=True, verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['customer_name'],
            },
        ),
    ]
