# Generated by Django 5.1.8 on 2025-04-28 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('original_org_id', models.IntegerField(help_text='ID of the organization as it existed before archival.', verbose_name='Original Organization ID')),
                ('customer_code', models.CharField(db_index=True, max_length=8, verbose_name='Customer Code')),
                ('customer_name', models.CharField(db_index=True, max_length=512, verbose_name='Customer Name')),
                ('archived_reason', models.TextField(blank=True, help_text='Reason this organization was archived or unsubscribed.', verbose_name='Reason for Archiving')),
                ('financial_year_end_date', models.DateField(blank=True, null=True, verbose_name='Financial Year End Date')),
                ('customer_industry', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Industry')),
                ('logo_path', models.CharField(blank=True, help_text='Path to the archived logo file (if retained).', max_length=512, null=True, verbose_name='Archived Logo Path')),
                ('was_active', models.BooleanField(default=True, help_text='Whether the organization was active at time of archival.', verbose_name='Was Active')),
            ],
            options={
                'verbose_name': 'Archived Organization',
                'verbose_name_plural': 'Archived Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this domain record was first created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this domain record was last modified', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tenant Domain',
                'verbose_name_plural': 'Tenant Domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(help_text='Postgres schema name for this tenant', max_length=63, unique=True)),
                ('name', models.CharField(default='Default Organization', help_text='The name of the organization', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the organization name', max_length=255, unique=True)),
                ('code', models.CharField(default='ORG001', help_text='Unique identifier code for the organization', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Only uppercase letters and numbers allowed')])),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=50)),
            ],
        ),
    ]
