# Generated by Django 5.1.8 on 2025-06-10 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedorganization',
            name='archived_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Archived By'),
        ),
        migrations.AddField(
            model_name='archivedorganization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='archivedorganization',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='organizations.organization', verbose_name='Organization')),
                ('subscription_plan', models.CharField(help_text="Identifier for the subscription plan (e.g., 'basic', 'premium').", max_length=50, verbose_name='Subscription Plan')),
                ('is_active', models.BooleanField(default=True, help_text="Indicates if the organization's subscription is active.", verbose_name='Active Status')),
                ('additional_settings', models.JSONField(blank=True, default=dict, help_text='A JSON field to store additional configuration parameters.', verbose_name='Additional Settings')),
                ('subscribed_apps', models.JSONField(blank=True, default=list, help_text='List of app codes this organization is subscribed to, e.g. ["audit", "risk", "legal", "compliance", "contracts", "document_management"]', verbose_name='Subscribed Apps')),
            ],
            options={
                'verbose_name': 'Organization Setting',
                'verbose_name_plural': 'Organization Settings',
                'ordering': ['organization__name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to='organizations.organization', verbose_name='Organization')),
                ('subscription_plan', models.CharField(help_text='The subscription plan for the organization (e.g., Basic, Premium).', max_length=50, verbose_name='Subscription Plan')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the subscription starts.', verbose_name='Subscription Start Date')),
                ('end_date', models.DateTimeField(help_text='The date when the subscription ends. Leave blank for ongoing subscriptions.', verbose_name='Subscription End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', help_text='Current status of the subscription.', max_length=20, verbose_name='Subscription Status')),
                ('auto_renew', models.BooleanField(default=True, help_text='Determines if the subscription automatically renews when it expires.', verbose_name='Auto Renew')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle period, e.g., monthly or yearly.', max_length=20, verbose_name='Billing Cycle')),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='The date of the last successful payment.', null=True, verbose_name='Last Payment Date')),
                ('next_payment_date', models.DateTimeField(blank=True, help_text='The date for the upcoming scheduled payment.', null=True, verbose_name='Next Payment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('id__isnull', False)), name='organization_required_organization'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='archivedorganization',
            index=models.Index(fields=['customer_code'], name='organizatio_custome_243b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedorganization',
            index=models.Index(fields=['customer_name'], name='organizatio_custome_de1ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedorganization',
            index=models.Index(fields=['archived_by_user'], name='organizatio_archive_b0d16c_idx'),
        ),
        migrations.AddConstraint(
            model_name='archivedorganization',
            constraint=models.CheckConstraint(condition=models.Q(('original_org_id__isnull', False)), name='organization_required_archivedorganization'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain'], name='organizatio_domain_cf1475_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['tenant'], name='organizatio_tenant__cada17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('domain', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='organizationsettings',
            index=models.Index(fields=['subscription_plan'], name='organizatio_subscri_a80384_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsettings',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_177a59_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationsettings',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_organizationsettings'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_plan'], name='organizatio_subscri_f1da97_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='organizatio_status_e8c375_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_subscription'),
        ),
    ]
