# Generated by Django 5.2 on 2025-04-14 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedorganization',
            name='archived_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Archived By'),
        ),
        migrations.AddField(
            model_name='archivedorganization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='archivedorganization',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='organizations.organization', verbose_name='Organization')),
                ('subscription_plan', models.CharField(help_text="Identifier for the subscription plan (e.g., 'basic', 'premium').", max_length=50, verbose_name='Subscription Plan')),
                ('is_active', models.BooleanField(default=True, help_text="Indicates if the organization's subscription is active.", verbose_name='Active Status')),
                ('additional_settings', models.JSONField(blank=True, default=dict, help_text='A JSON field to store additional configuration parameters.', verbose_name='Additional Settings')),
            ],
            options={
                'verbose_name': 'Organization Setting',
                'verbose_name_plural': 'Organization Settings',
                'ordering': ['organization__customer_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to='organizations.organization', verbose_name='Organization')),
                ('subscription_plan', models.CharField(help_text='The subscription plan for the organization (e.g., Basic, Premium).', max_length=50, verbose_name='Subscription Plan')),
                ('start_date', models.DateField(help_text='The date when the subscription starts.', verbose_name='Subscription Start Date')),
                ('end_date', models.DateField(blank=True, help_text='The date when the subscription ends. Leave blank for ongoing subscriptions.', null=True, verbose_name='Subscription End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', help_text='Current status of the subscription.', max_length=20, verbose_name='Subscription Status')),
                ('auto_renew', models.BooleanField(default=True, help_text='Determines if the subscription automatically renews when it expires.', verbose_name='Auto Renew')),
                ('billing_cycle', models.CharField(help_text='Billing cycle period, e.g., monthly or yearly.', max_length=20, verbose_name='Billing Cycle')),
                ('last_payment_date', models.DateField(blank=True, help_text='The date of the last successful payment.', null=True, verbose_name='Last Payment Date')),
                ('next_payment_date', models.DateField(blank=True, help_text='The date for the upcoming scheduled payment.', null=True, verbose_name='Next Payment Date')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='archivedorganization',
            index=models.Index(fields=['customer_code'], name='organizatio_custome_243b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedorganization',
            index=models.Index(fields=['customer_name'], name='organizatio_custome_de1ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedorganization',
            index=models.Index(fields=['archived_by_user'], name='organizatio_archive_b0d16c_idx'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['customer_code'], name='organizatio_custome_c5ced0_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['customer_name'], name='organizatio_custome_7c1455_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['customer_industry'], name='organizatio_custome_59c568_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsettings',
            index=models.Index(fields=['subscription_plan'], name='organizatio_subscri_a80384_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsettings',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_177a59_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_plan'], name='organizatio_subscri_f1da97_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='organizatio_status_e8c375_idx'),
        ),
    ]
