# Generated by Django 5.1.8 on 2025-04-30 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='archivedorganization',
            constraint=models.CheckConstraint(condition=models.Q(('original_org_id__isnull', False)), name='organization_required_archivedorganization'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('id__isnull', False)), name='organization_required_organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationsettings',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_organizationsettings'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False)), name='organization_required_subscription'),
        ),
    ]
