# Generated by Django 5.1.8 on 2025-05-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_archivedorganization_organization_required_archivedorganization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='subscribed_apps',
            field=models.JSONField(blank=True, default=list, help_text='List of app codes this organization is subscribed to, e.g. ["audit", "risk", "legal", "compliance", "contracts", "document_management"]', verbose_name='Subscribed Apps'),
        ),
    ]
